package ppimapbuilder.changelog.presentation;

import cytoscape.Cytoscape;
import java.awt.KeyboardFocusManager;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextArea;
import ppimapbuilder.changelog.ChangelogFrameControl;
import ppimapbuilder.creditframe.presentation.EscapeCloseListener;

/**
 *
 * @author CORNUT, CRESSANT, DUPUIS, GRAVOUIL
 */
public class ChangelogFrame extends javax.swing.JFrame {

    /**
     * Instance of the PPiMapBuilder changelog frame to prevent several
     * instances
     */
    private static final long serialVersionUID = 1L;
    /**
     * Instance of the PPiMapBuilder changelog frame to prevent several
     * instances
     */
    private static ChangelogFrame _instance = null;
    /**
     * Manage 'escape' hit
     */
    private EscapeCloseListener escapeListener;

    /**
     * Creates new form ChangelogFrame
     */
    private ChangelogFrame() {
        initComponents();

        // The frame is now centered relatively to Cytoscape
        this.setLocationRelativeTo(Cytoscape.getDesktop());

        // Close window on escape key
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        escapeListener = new EscapeCloseListener(this);
        manager.addKeyEventDispatcher(escapeListener);
    }

    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public JCheckBox getChkBoxShowAgain() {
        return chkBoxShowAgain;
    }

    public JTextArea getTxtareaChnglog() {
        return txtareaChnglog;
    }


    /**
     * Method to access the unique instance of Changlog
     *
     * @return _instance
     */
    public static ChangelogFrame Instance() {
        if (_instance == null) {
            _instance = new ChangelogFrame();
        }
        return _instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBottom = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        chkBoxShowAgain = new javax.swing.JCheckBox();
        pntTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        scrollPaneChnglog = new javax.swing.JScrollPane();
        txtareaChnglog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PPiMapBuilder - Changelog");
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(401, 301));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        btnSubmit.setText("Close");

        chkBoxShowAgain.setText("Show next time");

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(chkBoxShowAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(31, 31, 31))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(chkBoxShowAgain))
                .addContainerGap())
        );

        btnSubmit.addActionListener(new ChangeLogCloseListener(this));

        getContentPane().add(pnlBottom, java.awt.BorderLayout.SOUTH);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PPiMapBuilder v0.9 - Changelog");
        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        lblTitle.setPreferredSize(new java.awt.Dimension(350, 45));

        javax.swing.GroupLayout pntTopLayout = new javax.swing.GroupLayout(pntTop);
        pntTop.setLayout(pntTopLayout);
        pntTopLayout.setHorizontalGroup(
            pntTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pntTopLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pntTopLayout.setVerticalGroup(
            pntTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntTopLayout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getContentPane().add(pntTop, java.awt.BorderLayout.NORTH);

        scrollPaneChnglog.setAutoscrolls(true);

        txtareaChnglog.setEditable(false);
        txtareaChnglog.setColumns(20);
        txtareaChnglog.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtareaChnglog.setLineWrap(true);
        txtareaChnglog.setRows(5);
        txtareaChnglog.setWrapStyleWord(true);
        txtareaChnglog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtareaChnglog.setMargin(new java.awt.Insets(5, 5, 5, 5));
        scrollPaneChnglog.setViewportView(txtareaChnglog);
        ChangelogFrameControl.setChangelogText(this);

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneChnglog, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneChnglog, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkBoxShowAgain;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pntTop;
    private javax.swing.JScrollPane scrollPaneChnglog;
    private javax.swing.JTextArea txtareaChnglog;
    // End of variables declaration//GEN-END:variables
}
